{{$namespace := include "vechr.namespace" .}}
{{$releasename := include "vechr.releasename" .}}
{{if .Values.grafana.enabled}}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: datasource-grafana
  namespace: {{$namespace}}
data:
  datasource.yaml: | 
    {{- toYaml .Values.grafana.datasource | nindent 6}}
    
{{end}}
    