{{$namespace := include "vechr.namespace" .}}
{{$releasename := include "vechr.releasename" .}}
{{if .Values.grafana.enabled}}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana-{{$releasename}}
  namespace: {{ $namespace }}
  labels:
    app.kubernetes.io/component: vechr-grafana
    app.kubernetes.io/name: grafana
    app.kubernetes.io/part-of: vechr-monitoring
    app.kubernetes.io/version: {{.Values.grafana.image.tag}}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: vechr-grafana
      app.kubernetes.io/name: grafana
      app.kubernetes.io/part-of: vechr-monitoring
  template:
    metadata:
      name: grafana-{{$releasename}}
      labels:
        app.kubernetes.io/component: vechr-grafana
        app.kubernetes.io/name: grafana
        app.kubernetes.io/part-of: vechr-monitoring
    spec:
      restartPolicy: {{.Values.grafana.image.restartPolicy | default "Always"}}
      containers:
        - name: grafana-{{$releasename}}
          image: {{.Values.grafana.image.name}}:{{.Values.grafana.image.tag}}
          ports:
            - name: http
              containerPort: {{.Values.grafana.port}}
              protocol: TCP
          imagePullPolicy: {{.Values.grafana.image.imagePullPolicy | default "Always"}}
          env:
            {{range $i, $env_value := .Values.grafana.env}}
            - name: {{$env_value.name}}
              value: {{quote $env_value.value}}
            {{end}}
          volumeMounts:
          - name: datasource-config-volume
            mountPath: /etc/grafana/provisioning/datasources/datasource.yaml
            subPath: datasource.yaml

      volumes:
        - name: datasource-config-volume
          configMap:
            name: datasource-grafana

{{end}}