{{if .Values.grafana.enabled}}
---
apiVersion: v1
kind: Service
metadata:
  name: grafana-service
  namespace: {{ include "vechr.namespace" . }}
  labels:
    svc: vechr-grafana-service
spec:
  type: ClusterIP
  selector:
    svc: vechr-grafana-service
  ports:
    - port: 3000
      name: grafana-dashboard
      targetPort: 3000

{{end}}