{{if .Values.grafana.enabled}}
---
apiVersion: v1
kind: Service
metadata:
  name: grafana-service
  namespace: {{ include "vechr.namespace" . }}
  labels:
    app.kubernetes.io/component: vechr-grafana
    app.kubernetes.io/name: grafana
    app.kubernetes.io/part-of: vechr-monitoring
    app.kubernetes.io/version: {{.Values.grafana.image.tag}}
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/component: vechr-grafana
    app.kubernetes.io/name: grafana
    app.kubernetes.io/part-of: vechr-monitoring
  ports:
    - port: 3000
      name: grafana-dashboard
      targetPort: 3000

{{end}}