{{$namespace := include "vechr.namespace" .}}
{{$releasename := include "vechr.releasename" .}}
{{if .Values.grafana.enabled}}
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app.kubernetes.io/component: vechr-grafana
    app.kubernetes.io/name: grafana
    app.kubernetes.io/part-of: vechr-monitoring
    app.kubernetes.io/version: {{.Values.grafana.image.tag}}
  name: grafana-{{$releasename}}
  namespace: {{$namespace}}
spec:
  endpoints:
  - interval: 15s
    port: grafana-dashboard
  selector:
    matchLabels:
      app.kubernetes.io/component: vechr-grafana
      app.kubernetes.io/name: grafana
      app.kubernetes.io/part-of: vechr-monitoring

{{end}}
