apiVersion: v1
entries:
  vechr-iiot:
  - apiVersion: v2
    appVersion: 0.0.1
    created: "2023-06-10T18:46:09.676021206Z"
    dependencies:
    - condition: nats.enabled
      name: nats
      repository: https://nats-io.github.io/k8s/helm/charts/
      version: 1.0.0-beta.5
    - condition: nginx.enabled
      name: nginx-ingress
      repository: https://helm.nginx.com/stable
      version: 0.15.2
    - condition: postgresql.enabled
      name: postgresql
      repository: https://charts.bitnami.com/bitnami
      version: 12.1.6
    description: Helm Chart for Vechr Kubernetes
    digest: 98b1599e5ce43192f5db51fe4c69824dd2dc992390274a2b7b015eb246ca6696
    home: https://github.com/vechr/k8s
    icon: https://raw.githubusercontent.com/vechr/k8s/master/images/vechrk8s.svg
    keywords:
    - Vechr
    - IoT
    maintainers:
    - email: isnaen70@gmail.com
      name: zulfikar
      url: https://github.com/zulfikar4568
    name: vechr-iiot
    type: application
    urls:
    - https://github.com/vechr/k8s/releases/download/vechr-iiot-0.0.5/vechr-iiot-0.0.5.tgz
    version: 0.0.5
  - apiVersion: v2
    appVersion: 0.0.1
    created: "2023-06-10T18:19:45.989289197Z"
    dependencies:
    - condition: nats.enabled
      name: nats
      repository: https://nats-io.github.io/k8s/helm/charts/
      version: 1.0.0-beta.5
    - condition: nginx.enabled
      name: nginx-ingress
      repository: https://helm.nginx.com/stable
      version: 0.15.2
    - condition: postgresql.enabled
      name: postgresql
      repository: https://charts.bitnami.com/bitnami
      version: 12.1.6
    description: Helm Chart for Vechr Kubernetes
    digest: b13ba33bbb3bbbfb7471180f41b275b99b9e7862ec5d3a905f7fce641fdeb1c2
    home: https://github.com/vechr/k8s
    icon: https://raw.githubusercontent.com/vechr/k8s/master/images/vechrk8s.svg
    keywords:
    - Vechr
    - IoT
    maintainers:
    - email: isnaen70@gmail.com
      name: zulfikar
      url: https://github.com/zulfikar4568
    name: vechr-iiot
    type: application
    urls:
    - https://github.com/vechr/k8s/releases/download/vechr-iiot-0.0.4/vechr-iiot-0.0.4.tgz
    version: 0.0.4
  - apiVersion: v2
    appVersion: 0.0.1
    created: "2023-06-10T05:38:08.032831831Z"
    dependencies:
    - condition: nats.enabled
      name: nats
      repository: https://nats-io.github.io/k8s/helm/charts/
      version: 1.0.0-beta.5
    - condition: nginx.enabled
      name: nginx-ingress
      repository: https://helm.nginx.com/stable
      version: 0.15.2
    - condition: postgresql.enabled
      name: postgresql
      repository: https://charts.bitnami.com/bitnami
      version: 12.1.6
    description: Helm Chart for Vechr Kubernetes
    digest: 54b3ddb9f861fe3f2fd504ab15d1294a36644dbe4a2823b8eee2d2976fe50bdf
    home: https://github.com/vechr/k8s
    icon: https://raw.githubusercontent.com/vechr/k8s/master/images/vechrk8s.svg
    keywords:
    - Vechr
    - IoT
    maintainers:
    - email: isnaen70@gmail.com
      name: zulfikar
      url: https://github.com/zulfikar4568
    name: vechr-iiot
    type: application
    urls:
    - https://github.com/vechr/k8s/releases/download/vechr-iiot-0.0.3/vechr-iiot-0.0.3.tgz
    version: 0.0.3
  - apiVersion: v2
    appVersion: 0.0.1
    created: "2023-06-09T18:42:27.644109872Z"
    dependencies:
    - condition: nats.enabled
      name: nats
      repository: https://nats-io.github.io/k8s/helm/charts/
      version: 1.0.0-beta.5
    - condition: nginx.enabled
      name: nginx-ingress
      repository: https://helm.nginx.com/stable
      version: 0.15.2
    - condition: postgresql.enabled
      name: postgresql
      repository: https://charts.bitnami.com/bitnami
      version: 12.1.6
    description: Helm Chart for Vechr Kubernetes
    digest: aead3998ee512561575db0e5b59bc28319916f5dbef84beeb35ec77170ff13da
    home: https://github.com/vechr/k8s
    icon: https://raw.githubusercontent.com/vechr/k8s/master/images/vechrk8s.svg
    keywords:
    - Vechr
    - IoT
    maintainers:
    - email: isnaen70@gmail.com
      name: zulfikar
      url: https://github.com/zulfikar4568
    name: vechr-iiot
    type: application
    urls:
    - https://github.com/vechr/k8s/releases/download/vechr-iiot-0.0.2/vechr-iiot-0.0.2.tgz
    version: 0.0.2
  - apiVersion: v2
    appVersion: 0.0.1
    created: "2023-06-10T01:29:28.566517+07:00"
    dependencies:
    - condition: nats.enabled
      name: nats
      repository: https://nats-io.github.io/k8s/helm/charts/
      version: 1.0.0-beta.5
    - condition: nginx.enabled
      name: nginx-ingress
      repository: https://helm.nginx.com/stable
      version: 0.15.2
    - condition: postgresql.enabled
      name: postgresql
      repository: https://charts.bitnami.com/bitnami
      version: 12.1.6
    description: Helm Chart for Vechr Kubernetes
    digest: a11e754471ec0276e92d5d673d2c47850167988fecd140c99426da19cba056a1
    home: https://github.com/vechr/k8s
    icon: https://raw.githubusercontent.com/vechr/k8s/master/images/vechrk8s.svg
    keywords:
    - Vechr
    - IoT
    maintainers:
    - email: isnaen70@gmail.com
      name: zulfikar
      url: https://github.com/zulfikar4568
    name: vechr-iiot
    type: application
    urls:
    - https://github.com/vechr/k8s/releases/download/vechr-iiot-0.0.1/vechr-iiot-0.0.1.tgz
    version: 0.0.1
generated: "2023-06-10T18:46:09.676048607Z"
