{{$namespace := include "vechr.namespace" .}}
{{range $i, $value := .Values.serviceExternal.services | default dict}}
{{if $value.enabled}}
---
apiVersion: v1
kind: Service
metadata:
  name: {{$value.name}}
  namespace: {{ $namespace }}
  labels:
    app.kubernetes.io/component: vechr-external-service
    app.kubernetes.io/instance: vechr-external-service-{{$value.name}}
    app.kubernetes.io/name: external-service
    app.kubernetes.io/part-of: vechr-iiot
spec:
  type: ExternalName
  externalName: {{$value.externalName}}
  ports:
  {{range $j, $port := $value.ports | default dict}}
  - port: {{$port.port}}
  {{end}}
{{end}}
{{end}}