{{if .Values.certmanager.ingressTLS.enabled}}
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  labels:
    app.kubernetes.io/component: vechr-certmanager
    app.kubernetes.io/instance: vechr-certmanager-{{ .Values.certmanager.ingressTLS.issuer.name }}
    app.kubernetes.io/name: certmanager
    app.kubernetes.io/part-of: vechr-iiot
  name: {{ .Values.certmanager.ingressTLS.issuer.name }}
  namespace: {{ include "vechr.namespace" . }}
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: {{ .Values.certmanager.ingressTLS.issuer.email }}
    privateKeySecretRef:
      name: {{ .Values.certmanager.ingressTLS.issuer.name }}
    solvers:
    - http01:
        ingress:
          name: {{.Values.ingresses.name}}
{{end}}