{{if .Values.certmanager.ingressTLS.enabled}}
---
apiVersion: v1
kind: Secret
metadata:
  labels:
    app.kubernetes.io/component: vechr-certmanager
    app.kubernetes.io/instance: vechr-certmanager-{{ .Values.certmanager.ingressTLS.issuer.name }}
    app.kubernetes.io/name: certmanager
    app.kubernetes.io/part-of: vechr-iiot
  name: {{ .Values.certmanager.ingressTLS.name }}
  namespace: {{ include "vechr.namespace" . }}
type: kubernetes.io/tls
stringData:
  tls.key: ""
  tls.crt: ""
{{end}}