{{$namespace := include "vechr.namespace" .}}
{{$releasename := include "vechr.releasename" .}}
{{if .Values.alertmanager.enabled}}
---
apiVersion: monitoring.coreos.com/v1
kind: Alertmanager
metadata:
  labels:
    app.kubernetes.io/component: vechr-alertmanager
    app.kubernetes.io/instance: alertmanager-{{$releasename}}
    app.kubernetes.io/name: alertmanager
    app.kubernetes.io/part-of: vechr-monitoring
    app.kubernetes.io/version: 0.25.0
  name: alertmanager-{{$releasename}}
  namespace: {{$namespace}}
spec:
  image: quay.io/prometheus/alertmanager:v0.25.0
  nodeSelector:
    kubernetes.io/os: linux
  podMetadata:
    labels:
      app.kubernetes.io/component: vechr-alertmanager
      app.kubernetes.io/instance: alertmanager-{{$releasename}}
      app.kubernetes.io/name: alertmanager
      app.kubernetes.io/part-of: vechr-monitoring
      app.kubernetes.io/version: 0.25.0
  replicas: {{.Values.alertmanager.replicas | default 3}}
  resources:
    limits:
      cpu: 100m
      memory: 100Mi
    requests:
      cpu: 4m
      memory: 100Mi
  securityContext:
    fsGroup: 2000
    runAsNonRoot: true
    runAsUser: 1000
  serviceAccountName: alertmanager-{{$releasename}}
  version: 0.25.0

{{end}}
