{{$namespace := include "vechr.namespace" .}}
{{$releasename := include "vechr.releasename" .}}
{{if .Values.alertmanager.enabled}}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: vechr-alertmanager
    app.kubernetes.io/instance: alertmanager-{{$releasename}}
    app.kubernetes.io/name: alertmanager
    app.kubernetes.io/part-of: vechr-monitoring
    app.kubernetes.io/version: 0.25.0
  name: alertmanager-{{$releasename}}
  namespace: {{$namespace}}
spec:
  ports:
  - name: web
    port: 9093
    targetPort: web
  - name: reloader-web
    port: 8080
    targetPort: reloader-web
  selector:
    app.kubernetes.io/component: vechr-alertmanager
    app.kubernetes.io/instance: alertmanager-{{$releasename}}
    app.kubernetes.io/name: alertmanager
    app.kubernetes.io/part-of: vechr-monitoring
  sessionAffinity: ClientIP

{{end}}