{{$namespace := include "vechr.namespace" .}}
{{$releasename := include "vechr.releasename" .}}
{{if .Values.alertmanager.enabled}}
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app.kubernetes.io/component: vechr-alertmanager
    app.kubernetes.io/instance: alertmanager-{{$releasename}}
    app.kubernetes.io/name: alertmanager
    app.kubernetes.io/part-of: vechr-monitoring
    app.kubernetes.io/version: 0.25.0
  name: alertmanager-{{$releasename}}
  namespace: {{$namespace}}
spec:
  endpoints:
  - interval: 30s
    port: web
  - interval: 30s
    port: reloader-web
  selector:
    matchLabels:
      app.kubernetes.io/component: vechr-alertmanager
      app.kubernetes.io/instance: alertmanager-{{$releasename}}
      app.kubernetes.io/name: alertmanager
      app.kubernetes.io/part-of: vechr-monitoring

{{end}}