apiVersion: v2
appVersion: "0.0.1"

name: vechr-iiot
description: Helm Chart for Vechr Kubernetes
keywords:
- Vechr
- IoT

type: application
version: 0.0.1
home: https://github.com/vechr/k8s
maintainers:
  - name: zulfikar
    url: https://github.com/zulfikar4568
    email: isnaen70@gmail.com
icon: https://raw.githubusercontent.com/vechr/k8s/master/images/vechrk8s.svg


dependencies:
  - name: nats
    version: 1.0.0-beta.5
    repository: https://nats-io.github.io/k8s/helm/charts/
    condition: nats.enabled
  
  - name: nginx-ingress
    version: 0.15.2
    repository: https://helm.nginx.com/stable
    condition: nginx.enabled

  - name: postgresql
    version: 12.1.6
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled