{{$namespace := include "vechr.namespace" .}}
{{$releasename := include "vechr.releasename" .}}
{{if .Values.kubeStateMetrics.enabled}}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app.kubernetes.io/component: vechr-exporter
    app.kubernetes.io/name: kube-state-metrics
    app.kubernetes.io/part-of: vechr-monitoring
    app.kubernetes.io/version: 2.9.2
  name: kube-state-metrics-{{$releasename}}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kube-state-metrics-{{$releasename}}
subjects:
- kind: ServiceAccount
  name: kube-state-metrics-{{$releasename}}
  namespace: {{$namespace}}

{{end}}