{{$namespace := include "vechr.namespace" .}}
{{$releasename := include "vechr.releasename" .}}
{{if .Values.kubeStateMetrics.enabled}}
---
apiVersion: v1
automountServiceAccountToken: false
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/component: vechr-exporter
    app.kubernetes.io/name: kube-state-metrics
    app.kubernetes.io/part-of: vechr-monitoring
    app.kubernetes.io/version: 2.9.2
  name: kube-state-metrics-{{$releasename}}
  namespace: {{$namespace}}

{{end}}
