{{if .Values.ingress.tls.enabled }}
---
apiVersion: v1
kind: Secret
metadata:
  labels:
    app.kubernetes.io/component: vechr-ingress
    app.kubernetes.io/instance: vechr-ingress-{{.Values.ingress.name}}
    app.kubernetes.io/name: ingress
    app.kubernetes.io/part-of: vechr-iiot
  name: {{.Values.ingress.tls.secretName}}
  namespace: {{ include "vechr.namespace" . }}
type: kubernetes.io/tls
data:
  ca.crt: {{.Values.ingress.tls.ca}}
  tls.crt: {{.Values.ingress.tls.cert}}
  tls.key: {{.Values.ingress.tls.key}}
{{end}}