apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: nats
  name: nats-lb
  namespace: {{ include "vechr.namespace" . }}
  {{if .Values.gke.enabled}}
  annotations:
    cloud.google.com/l4-rbs: "enabled"
  {{end}}
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: nats
  ports:
    - protocol: TCP
      port: {{ .Values.nats.config.nats.port }}
      targetPort: {{ .Values.nats.config.nats.port }}
      name: nats
    - protocol: TCP
      port: {{ .Values.nats.config.mqtt.port }}
      targetPort: {{ .Values.nats.config.mqtt.port }}
      name: mqtt
    - protocol: TCP
      port: {{ .Values.nats.config.websocket.port }}
      targetPort: {{ .Values.nats.config.websocket.port }}
      name: websocket
    - protocol: TCP
      port: {{ .Values.nats.config.leafnodes.port }}
      targetPort: {{ .Values.nats.config.leafnodes.port }}
      name: leafnodes
  {{if .Values.gke.enabled}}
  loadBalancerIP: {{ .Values.gke.nats.loadBalancerIP | quote }}
  externalTrafficPolicy: Cluster
  {{end}}