apiVersion: v1
kind: Secret
metadata:
  labels:
    app.kubernetes.io/name: nats
  name: {{.Values.natsSelfSigned.secretName}}
  namespace: {{ include "vechr.namespace" . }}
type: kubernetes.io/tls
data:
  ca.crt: {{.Values.natsSelfSigned.ca}}
  tls.crt: {{.Values.natsSelfSigned.cert}}
  tls.key: {{.Values.natsSelfSigned.key}}