{{$namespace := include "vechr.namespace" .}}
{{$releasename := include "vechr.releasename" .}}
{{if .Values.nodeExporter.enabled}}
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  labels:
    app.kubernetes.io/component: vechr-exporter
    app.kubernetes.io/name: node-exporter
    app.kubernetes.io/part-of: vechr-monitoring
    app.kubernetes.io/version: 1.6.1
  name: node-exporter-{{$releasename}}
  namespace: {{$namespace}}
spec:
  egress:
  - {}
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app.kubernetes.io/name: prometheus
    ports:
    - port: 9100
      protocol: TCP
  podSelector:
    matchLabels:
      app.kubernetes.io/component: vechr-exporter
      app.kubernetes.io/name: node-exporter
      app.kubernetes.io/part-of: vechr-monitoring
  policyTypes:
  - Egress
  - Ingress

{{end}}
