{{$namespace := include "vechr.namespace" .}}
{{$releasename := include "vechr.releasename" .}}
{{if .Values.nodeExporter.enabled}}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: vechr-exporter
    app.kubernetes.io/name: node-exporter
    app.kubernetes.io/part-of: vechr-monitoring
    app.kubernetes.io/version: 1.6.1
  name: node-exporter-service
  namespace: {{$namespace}}
spec:
  clusterIP: None
  ports:
  - name: https
    port: 9100
    targetPort: https
  selector:
    app.kubernetes.io/component: vechr-exporter
    app.kubernetes.io/name: node-exporter
    app.kubernetes.io/part-of: vechr-monitoring
  
{{end}}
