{{$namespace := include "vechr.namespace" .}}
{{$releasename := include "vechr.releasename" .}}
{{if .Values.prometheus.enabled}}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app.kubernetes.io/component: vechr-prometheus-operator
    app.kubernetes.io/name: vechr-prometheus-operator
    app.kubernetes.io/part-of: vechr-monitoring
    app.kubernetes.io/version: 0.66.0
  name: prometheus-operator-{{$releasename}}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: prometheus-operator-{{$releasename}}
subjects:
- kind: ServiceAccount
  name: prometheus-operator-{{$releasename}}
  namespace: {{$namespace}}

{{end}}
