{{if .Values.influx.enabled}}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ default "influxdb" .Values.influx.name }}-config
  namespace: {{ include "vechr.namespace" . }}
  labels:
    app.kubernetes.io/component: vechr-influxdb
    app.kubernetes.io/instance: {{ default "influxdb" .Values.influx.name }}
    app.kubernetes.io/name: influxdb
    app.kubernetes.io/part-of: vechr-iiot
    app.kubernetes.io/version: {{ default "2.1.0-alpine" .Values.influx.deployment.tag }}
data:
  DOCKER_INFLUXDB_INIT_MODE: {{ default "setup" .Values.influx.influx.mode }}
  DOCKER_INFLUXDB_INIT_USERNAME: {{ default "admin" .Values.influx.auth.username }}
  DOCKER_INFLUXDB_INIT_PASSWORD: {{ default "password123" .Values.influx.auth.password }}
  DOCKER_INFLUXDB_INIT_ORG: {{ default "Vechr" .Values.influx.influx.organization }}
  DOCKER_INFLUXDB_INIT_BUCKET: {{ default "Vechr" .Values.influx.influx.bucket }}
  DOCKER_INFLUXDB_INIT_ADMIN_TOKEN: {{ default "vechr-token" .Values.influx.influx.token }}

{{end}}