{{if .Values.influx.enabled}}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ default "influxdb" .Values.influx.name }}-service
  namespace: {{ include "vechr.namespace" . }}
  labels:
    app: {{ default "influxdb" .Values.influx.name }}
spec:
  type: ClusterIP
  selector:
    app: {{ default "influxdb" .Values.influx.name }}
  ports:
    - protocol: TCP
      name: http
      port: {{ default 8086 .Values.influx.influx.port }}
      targetPort: 8086

{{end}}