{{if .Values.influx.enabled}}
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ default "influxdb" .Values.influx.name }}
  namespace: {{ include "vechr.namespace" . }}
  labels:
    app.kubernetes.io/component: vechr-influxdb
    app.kubernetes.io/instance: {{ default "influxdb" .Values.influx.name }}
    app.kubernetes.io/name: influxdb
    app.kubernetes.io/part-of: vechr-iiot
    app.kubernetes.io/version: {{ default "2.1.0-alpine" .Values.influx.deployment.tag }}
spec:
  serviceName: {{ default "influxdb" .Values.influx.name }}-service
  replicas: {{ default 1 .Values.influx.replicas }}
  selector:
    matchLabels:
      app.kubernetes.io/component: vechr-influxdb
      app.kubernetes.io/instance: {{ default "influxdb" .Values.influx.name }}
      app.kubernetes.io/name: influxdb
      app.kubernetes.io/part-of: vechr-iiot
  volumeClaimTemplates:
    - metadata:
        name: {{ default "influxdb" .Values.influx.name }}-pvc
      spec:
        accessModes:
          - ReadWriteOnce
        volumeMode: Filesystem
        resources:
          requests:
            storage: 2Gi
  template:
    metadata:
      name: {{ default "influxdb" .Values.influx.name }}
      labels:
        app.kubernetes.io/component: vechr-influxdb
        app.kubernetes.io/instance: {{ default "influxdb" .Values.influx.name }}
        app.kubernetes.io/name: influxdb
        app.kubernetes.io/part-of: vechr-iiot
        app.kubernetes.io/version: {{ default "2.1.0-alpine" .Values.influx.deployment.tag }}
    spec:
      containers:
        - name: {{ default "influxdb" .Values.influx.name }}
          image: {{ default "influxdb" .Values.influx.deployment.image }}:{{ default "2.1.0-alpine" .Values.influx.deployment.tag }}
          imagePullPolicy: "IfNotPresent"
          ports:
          - containerPort: {{ .Values.influx.deployment.port }}
          envFrom:
            - configMapRef:
                name: {{ default "influxdb" .Values.influx.name }}-config
          volumeMounts:
            - mountPath: /var/lib/influxdb
              name: {{ default "influxdb" .Values.influx.name }}-pvc

{{end}}