{{$namespace := include "vechr.namespace" .}}
{{$releasename := include "vechr.releasename" .}}
{{if .Values.prometheus.enabled}}
---
apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  labels:
    app.kubernetes.io/component: vechr-prometheus
    app.kubernetes.io/instance: prometheus-{{$releasename}}
    app.kubernetes.io/name: prometheus
    app.kubernetes.io/part-of: vechr-monitoring
    app.kubernetes.io/version: {{.Values.prometheus.image.tag}}
  name: prometheus-{{$releasename}}
  namespace: {{$namespace}}
spec:
  alerting:
    alertmanagers: {{.Values.prometheus.alertmanagers}}
  enableFeatures: {{.Values.prometheus.enableFeatures}}
  externalLabels: {}
  image: {{.Values.prometheus.image.name}}:v{{.Values.prometheus.image.tag}}
  nodeSelector:
    kubernetes.io/os: linux
  podMetadata:
    labels:
      app.kubernetes.io/component: vechr-prometheus
      app.kubernetes.io/instance: prometheus-{{$releasename}}
      app.kubernetes.io/name: prometheus
      app.kubernetes.io/part-of: vechr-monitoring
      app.kubernetes.io/version: {{.Values.prometheus.image.tag}}
  podMonitorSelector: {{(toYaml .Values.prometheus.podMonitorSelector | indent 4)}}
  probeNamespaceSelector: {{(toYaml .Values.prometheus.probeNamespaceSelector | indent 4)}}
  probeSelector: {{(toYaml .Values.prometheus.probeSelector | indent 4)}}
  replicas: {{.Values.prometheus.replicas}}
  resources:
    requests:
      memory: 400Mi
  ruleNamespaceSelector:  {{(toYaml .Values.prometheus.ruleNamespaceSelector | indent 4)}}
  ruleSelector: {{(toYaml .Values.prometheus.ruleSelector | indent 4)}}
  securityContext:
    fsGroup: 2000
    runAsNonRoot: true
    runAsUser: 1000
  serviceAccountName: {{.Values.prometheus.serviceAccount.name}}
  serviceMonitorNamespaceSelector: {{(toYaml .Values.prometheus.serviceMonitorNamespaceSelector | indent 4)}}
  serviceMonitorSelector: {{(toYaml .Values.prometheus.serviceMonitorSelector | indent 4)}}
  version: {{.Values.prometheus.image.tag}}

{{end}}