{{$namespace := include "vechr.namespace" .}}
{{$releasename := include "vechr.releasename" .}}
{{if .Values.prometheus.enabled}}
---
apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  labels:
    app.kubernetes.io/component: vechr-prometheus
    app.kubernetes.io/instance: prometheus-{{$releasename}}
    app.kubernetes.io/name: prometheus
    app.kubernetes.io/part-of: vechr-monitoring
    app.kubernetes.io/version: {{.Values.prometheus.image.tag}}
  name: prometheus-{{$releasename}}
  namespace: {{$namespace}}
spec:
  alerting:
    alertmanagers: {{.Values.prometheus.alertmanagers}}
  enableFeatures: {{.Values.prometheus.enableFeatures}}
  externalLabels: {}
  image: {{.Values.prometheus.image.name}}:v{{.Values.prometheus.image.tag}}
  nodeSelector:
    kubernetes.io/os: linux
  podMetadata:
    labels:
      app.kubernetes.io/component: vechr-prometheus
      app.kubernetes.io/instance: prometheus-{{$releasename}}
      app.kubernetes.io/name: prometheus
      app.kubernetes.io/part-of: vechr-monitoring
      app.kubernetes.io/version: {{.Values.prometheus.image.tag}}
  podMonitorSelector: {}
  probeNamespaceSelector: {}
  probeSelector: {}
  replicas: {{.Values.prometheus.replicas}}
  resources:
    requests:
      memory: 400Mi
  ruleNamespaceSelector: {}
  ruleSelector: {}
  securityContext:
    fsGroup: 2000
    runAsNonRoot: true
    runAsUser: 1000
  serviceAccountName: {{.Values.prometheus.serviceAccount.name}}
  serviceMonitorNamespaceSelector: {}
  serviceMonitorSelector: {}
  version: {{.Values.prometheus.image.tag}}

{{end}}