{{$namespace := include "vechr.namespace" .}}
{{$releasename := include "vechr.releasename" .}}
{{if .Values.prometheus.enabled}}
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app.kubernetes.io/component: vechr-prometheus
    app.kubernetes.io/instance: prometheus-{{$releasename}}
    app.kubernetes.io/name: prometheus
    app.kubernetes.io/part-of: vechr-monitoring
    app.kubernetes.io/version: {{.Values.prometheus.image.tag}}
  name: {{.Values.prometheus.serviceAccount.name}}
  namespace: {{$namespace}}
spec:
  endpoints:
  - interval: 30s
    port: web
  - interval: 30s
    port: reloader-web
  selector:
    matchLabels:
      app.kubernetes.io/component: vechr-prometheus
      app.kubernetes.io/instance: prometheus-{{$releasename}}
      app.kubernetes.io/name: prometheus
      app.kubernetes.io/part-of: vechr-monitoring

{{end}}
