{{if .Values.frontend.enabled}}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vechr-frontend-{{ .Values.frontend.name }}
  namespace: {{ include "vechr.namespace" . }}
  labels:
    app: vechr-frontend-{{ .Values.frontend.name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vechr-frontend-{{ .Values.frontend.name }}
  template:
    metadata:
      name: vechr-frontend-{{ .Values.frontend.name }}
      labels:
        app: vechr-frontend-{{ .Values.frontend.name }}
    spec:
      restartPolicy: Always
      containers:
        - name: vechr-frontend-{{ .Values.frontend.name }}
          image: {{.Values.frontend.image}}:{{.Values.frontend.tag}}
          {{if and .Values.frontend.externalPort .Values.frontend.port}}
          ports:
            - name: http
              containerPort: {{.Values.frontend.port}}
              protocol: TCP
          {{ end }}
          imagePullPolicy: {{.Values.frontend.imagePullPolicy | default "Always"}}

          # Resource Allocation
          {{- if .Values.frontend.resources }}
          resources:
            requests:
              memory: {{ .Values.frontend.resources.requests.memory | default "100Mi" | quote }}
              cpu: {{ .Values.frontend.resources.requests.cpu | default "100m" | quote }}
            limits:
              memory: {{ .Values.frontend.resources.limits.memory | default "1024Mi" | quote }}
              cpu: {{ .Values.frontend.resources.limits.cpu | default "1" | quote }}
          {{- end}}

{{end}}