{{$namespace := include "vechr.namespace" .}}
{{$releasename := include "vechr.releasename" .}}
{{if .Values.loki.enabled}}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: config-loki
  namespace: {{$namespace}}
data:
  config.yaml: |
    {{- toYaml .Values.loki.config | nindent 6}}
    
{{end}}