{{$namespace := include "vechr.namespace" .}}
{{$releasename := include "vechr.releasename" .}}
{{if .Values.loki.enabled}}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: loki-{{$releasename}}
  namespace: {{ $namespace }}
  labels:
    app.kubernetes.io/component: vechr-loki
    app.kubernetes.io/name: loki
    app.kubernetes.io/part-of: vechr-monitoring
    app.kubernetes.io/version: {{.Values.loki.image.tag}}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: vechr-loki
      app.kubernetes.io/name: loki
      app.kubernetes.io/part-of: vechr-monitoring
  template:
    metadata:
      name: loki-{{$releasename}}
      labels:
        app.kubernetes.io/component: vechr-loki
        app.kubernetes.io/name: loki
        app.kubernetes.io/part-of: vechr-monitoring
    spec:
      restartPolicy: {{.Values.loki.image.restartPolicy | default "Always"}}
      containers:
        - name: loki-{{$releasename}}
          image: {{.Values.loki.image.name}}:{{.Values.loki.image.tag}}
          args: ["-config.file=/etc/loki/config.yaml"]
          ports:
            - name: http
              containerPort: {{.Values.loki.port}}
              protocol: TCP
          imagePullPolicy: {{.Values.loki.image.imagePullPolicy | default "Always"}}
          env:
            {{range $i, $env_value := .Values.loki.env}}
            - name: {{$env_value.name}}
              value: {{quote $env_value.value}}
            {{end}}
          volumeMounts:
          - name: config-loki-volume
            mountPath: /etc/loki/config.yaml
            subPath: config.yaml

      volumes:
        - name: config-loki-volume
          configMap:
            name: config-loki

{{end}}