{{if .Values.loki.enabled}}
---
apiVersion: v1
kind: Service
metadata:
  name: loki-service
  namespace: {{ include "vechr.namespace" . }}
  labels:
    app.kubernetes.io/component: vechr-loki
    app.kubernetes.io/name: loki
    app.kubernetes.io/part-of: vechr-monitoring
    app.kubernetes.io/version: {{.Values.loki.image.tag}}
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/component: vechr-loki
    app.kubernetes.io/name: loki
    app.kubernetes.io/part-of: vechr-monitoring
  ports:
    - port: 3100
      name: loki-port
      targetPort: 3100

{{end}}