{{if .Values.loki.enabled}}
---
apiVersion: v1
kind: Service
metadata:
  name: loki-service
  namespace: {{ include "vechr.namespace" . }}
  labels:
    svc: vechr-loki-service
spec:
  type: ClusterIP
  selector:
    svc: vechr-loki-service
  ports:
    - port: 3100
      name: loki-port
      targetPort: 3100

{{end}}