{{$namespace := include "vechr.namespace" .}}
{{$releasename := include "vechr.releasename" .}}
{{if .Values.tempo.enabled}}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: config-tempo
  namespace: {{$namespace}}
data:
  config.yaml: |
    {{- toYaml .Values.tempo.config | nindent 6}}

{{end}}
    