{{if .Values.tempo.enabled}}
---
apiVersion: v1
kind: Service
metadata:
  name: tempo-service
  namespace: {{ include "vechr.namespace" . }}
  labels:
    app.kubernetes.io/component: vechr-tempo
    app.kubernetes.io/name: tempo
    app.kubernetes.io/part-of: vechr-monitoring
    app.kubernetes.io/version: {{.Values.tempo.image.tag}}
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/component: vechr-tempo
    app.kubernetes.io/name: tempo
    app.kubernetes.io/part-of: vechr-monitoring
  ports:
    - name: tempo-port
      port: 3200
      targetPort: 3200
    {{range $i, $port := .Values.tempo.ports}}
    - name: {{$port.name}}
      port: {{$port.containerPort}}
      targetPort: {{$port.containerPort}}
    {{end}}

{{end}}