{{if .Values.tempo.enabled}}
---
apiVersion: v1
kind: Service
metadata:
  name: tempo-service
  namespace: {{ include "vechr.namespace" . }}
  labels:
    svc: vechr-tempo-service
spec:
  type: ClusterIP
  selector:
    svc: vechr-tempo-service
  ports:
    {{range $i, $port := .Values.tempo.ports}}
    - name: {{$port.name}}
      port: {{$port.containerPort}}
      targetPort: {{$port.containerPort}}
    {{end}}

{{end}}